services:
  - type: web
    name: Starfield
    env: static
    staticPublishPath: ./starfield/
  - type: web
    name: Comet
    env: static
    staticPublishPath: ./comet/
  - this_is_a_typo: web
    name: Rocket
    env: static
    staticPublishPath: ./rocket/
